name: Periodic health check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'   # once per day (UTC)

jobs:
  health_check:
    runs-on: ubuntu-latest

    steps:
      - name: Check deployed app health
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://full-stack-open-pokedex-suoz.onrender.com
          max-attempts: 3
          retry-delay: 10s
